### PR TITLE
Add method to check all images in the page exist #17

### LINKED ISSUE #17: Add a method to do a HEAD or GET on all graphics referenced
When making my way through a clickpath, I'm not checking that all the graphics exist.

Add a method like `$mech->check_all_images()` that makes sure that all images exist.  A HEAD call instead of GET should suffice on each graphic.

### PR DESCRIPTION
**Pull request by simbabque**
This looked like a fun issue to attempt for Hacktoberfest. I think the functionality is done, but the new test is failing because it expects an extra newline at the end of the diagnostic output. I don't know why. Maybe you have an idea?

I also had to bump (well, require at least a specific version of) HTTP::Message because of libwww-perl/HTTP-Message#146 happening in my implementation, and I couldn't see a way to work around it. I'm not sure if I did that right, I am not familiar with using MakeMaker based distributions.

Closes #17

### CODE REVIEW

**Comment by petdance** [comment]
Wow, thanks for jumping on this.  I will try to look at this in depth today or tomorrow.

**Comment by simbabque** [comment]
Sorry, I was a bit busy. I've changed the name, and I think your additional features make a lot of sense. I still don't understand why the test doesn't work. It looks the same as all the others. I read through the Test::Builder code for it, but I can't figure it out.

**Comment by simbabque** [comment]
Right, I had some quiet time and went all in. It should now do everything you suggested in #17. You can pass in an optional full compliment of `find_all_images()` arguments and it caches the results it's already seen for the entire runtime. 

As discussed, I am bumping the Perl version to 5.10. That means you could undo d78b1678d20050434fb17725c01db6a0bce002cb, or at least remove the now slightly confusing _FIXES_ message in the Changes file saying code that didn't run on 5.10+ was removed.

I've updated the Changes file otherwise.

**Comment by simbabque** [comment]
I forgot to take the WIP out. This is all finished.

**Comment by simbabque** [comment]
Bump :)

**Comment by petdance** [comment]
Merged, and about to release 1.56.  Thanks.

**Comment by haarg** [comment]
A global cache that persists the lifetime of the process seems wrong for a module with an OO interface. I would think that the cache should be stored in the object, not globally with `state`.

**Comment by petdance** [comment]
It's both right and wrong, depending on use case. I've made a ticket to allow both at #78. Thanks for the nudge.

**Pull request merged**
