### PR TITLE
Modified messages clearer for existence of optional module #59

### LINKED ISSUE #59: Make messages clearer that HTML::Lint and HTML::Tidy5 are optional
@kmh had a build problem like this:

```
t/00-load.t ................ 1/1 # Testing Test::WWW::Mechanize 1.50, with WWW::Mechanize 1.88, LWP 6.05, Test::More 1.302136, Perl 5.018002, /usr/bin/perl
# Found HTML::Lint 2.30
# No HTML::Tidy5 found.
t/00-load.t ................ ok   
t/autolint.t ............... ok     
t/autotidy.t ............... skipped: HTML::Tidy5 1.00 is not installed, cannot test autotidy.
t/click_ok.t ............... # Test server http://127.0.0.1:21050 as PID 22126
t/click_ok.t ............... 1/3 
#   Failed test 'GET http://127.0.0.1:21050/form.html'
#   at t/click_ok.t line 21.
# 503
# Service Unavailable
Can't call method "click" on an undefined value at /usr/local/share/perl/5.18.2/WWW/Mechanize.pm line 934, <DATA> line 16.
# Looks like your test exited with 255 just after 2.
```

The first thing that jumped out was "No HTML::Tidy5 found" which led her to believe that that was the core problem.  Same with the "HTML::Tidy5 1.00 is not installed, cannot test autotidy"

Make the messages clearer that these are strictly optional.

### PR DESCRIPTION
**Pull request by mschae94**
fixes #59

### CODE REVIEW

**Comment by petdance** [comment]
Oh this is nice.  Thank you.  I will try to check it in tonight.

**Comment by petdance** [comment]
What's your name?  I'd like to list you in the acknowledgements.

**Comment by mschae94** [comment]
Thank you very much for taking my very first request. My name is Matthew Chae.

**Comment by petdance** [comment]
Thanks.  I've merged this and it will go out in the next release.  See 71f5066.

**Pull request merged**
