### PR TITLE
allow click_ok handle \$x & \$y  optionally Issue #45

### PR DESCRIPTION
**Pull request by marderh**
Fulfilling my CPAN PRC July assignment, I tried to adress Issue #45

### CODE REVIEW

**Comment by marderh** [comment]
Of course i'm open to critics, hintsor comments.

**Comment by petdance** [comment]
Nice.  That seems pretty reasonable.

**Comment by petdance** [comment]
I'm implementing this today.  Sorry it took years to get to.  :-(

**Comment by petdance** [comment]
This is done.  ae6cacc.  Thanks @marderh

We need more testing in t/click_ok.t, so that's now a ticket at #62

**Pull request closed without merging**
